-- 0001_core_schema.sql
-- Canonical PostgreSQL core schema for the Pokemon RPG engine.
-- IDs are generated by the application. Content seed/import is intentionally separate.

CREATE TABLE admin_principals (
  id UUID PRIMARY KEY,
  identity_ref TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('ACTIVE', 'DISABLED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE admin_roles (
  id UUID PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE capabilities (
  id UUID PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  risk_tier SMALLINT NOT NULL CHECK (risk_tier BETWEEN 0 AND 4),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE admin_role_capabilities (
  role_id UUID NOT NULL REFERENCES admin_roles(id),
  capability_id UUID NOT NULL REFERENCES capabilities(id),
  PRIMARY KEY (role_id, capability_id)
);

CREATE TABLE admin_principal_roles (
  principal_id UUID NOT NULL REFERENCES admin_principals(id),
  role_id UUID NOT NULL REFERENCES admin_roles(id),
  PRIMARY KEY (principal_id, role_id)
);

CREATE TABLE rulesets (
  id UUID PRIMARY KEY,
  key TEXT NOT NULL,
  version INTEGER NOT NULL CHECK (version > 0),
  engine_contract_version INTEGER NOT NULL CHECK (engine_contract_version > 0),
  config JSONB NOT NULL CHECK (jsonb_typeof(config) = 'object'),
  status TEXT NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at TIMESTAMPTZ NULL,
  UNIQUE (key, version),
  CHECK ((status = 'PUBLISHED' AND published_at IS NOT NULL) OR status <> 'PUBLISHED')
);

CREATE TABLE content_releases (
  id UUID PRIMARY KEY,
  release_no BIGINT NOT NULL UNIQUE CHECK (release_no > 0),
  name TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
  parent_release_id UUID NULL REFERENCES content_releases(id),
  default_ruleset_id UUID NOT NULL REFERENCES rulesets(id),
  created_by_admin_principal_id UUID NULL REFERENCES admin_principals(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at TIMESTAMPTZ NULL,
  CHECK (parent_release_id IS NULL OR parent_release_id <> id),
  CHECK ((status = 'PUBLISHED' AND published_at IS NOT NULL) OR status <> 'PUBLISHED')
);

CREATE TABLE pokemon_types (
  id UUID PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE
);

CREATE TABLE moves (
  id UUID PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE
);

CREATE TABLE abilities (
  id UUID PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE
);

CREATE TABLE items (
  id UUID PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE
);

CREATE TABLE natures (
  id UUID PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE
);

CREATE TABLE effects (
  id UUID PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE
);

CREATE TABLE pokemon_species (
  id UUID PRIMARY KEY,
  national_dex SMALLINT NOT NULL UNIQUE CHECK (national_dex > 0),
  slug TEXT NOT NULL UNIQUE
);

CREATE TABLE pokemon_forms (
  id UUID PRIMARY KEY,
  species_id UUID NOT NULL REFERENCES pokemon_species(id),
  slug TEXT NOT NULL,
  UNIQUE (species_id, slug)
);

CREATE TABLE regions (
  id UUID PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE
);

CREATE TABLE areas (
  id UUID PRIMARY KEY,
  region_id UUID NOT NULL REFERENCES regions(id),
  slug TEXT NOT NULL,
  UNIQUE (region_id, slug)
);

CREATE TABLE area_connections (
  id UUID PRIMARY KEY,
  from_area_id UUID NOT NULL REFERENCES areas(id),
  to_area_id UUID NOT NULL REFERENCES areas(id),
  connection_key TEXT NOT NULL,
  UNIQUE (from_area_id, to_area_id, connection_key),
  CHECK (from_area_id <> to_area_id)
);

CREATE TABLE encounter_tables (
  id UUID PRIMARY KEY,
  area_id UUID NOT NULL REFERENCES areas(id),
  slug TEXT NOT NULL,
  UNIQUE (area_id, slug)
);

CREATE TABLE currency_definitions (
  id UUID PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  allows_negative BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE pokemon_type_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  type_id UUID NOT NULL REFERENCES pokemon_types(id),
  display_name TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  data JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(data) = 'object'),
  UNIQUE (content_release_id, type_id)
);

CREATE TABLE pokemon_species_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  species_id UUID NOT NULL REFERENCES pokemon_species(id),
  display_name TEXT NOT NULL,
  catch_rate INTEGER NULL CHECK (catch_rate IS NULL OR catch_rate >= 0),
  base_exp INTEGER NULL CHECK (base_exp IS NULL OR base_exp >= 0),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  data JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(data) = 'object'),
  UNIQUE (content_release_id, species_id)
);

CREATE TABLE pokemon_form_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  form_id UUID NOT NULL REFERENCES pokemon_forms(id),
  display_name TEXT NOT NULL,
  type1_id UUID NOT NULL REFERENCES pokemon_types(id),
  type2_id UUID NULL REFERENCES pokemon_types(id),
  base_hp SMALLINT NOT NULL CHECK (base_hp > 0),
  base_attack SMALLINT NOT NULL CHECK (base_attack > 0),
  base_defense SMALLINT NOT NULL CHECK (base_defense > 0),
  base_sp_attack SMALLINT NOT NULL CHECK (base_sp_attack > 0),
  base_sp_defense SMALLINT NOT NULL CHECK (base_sp_defense > 0),
  base_speed SMALLINT NOT NULL CHECK (base_speed > 0),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  data JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(data) = 'object'),
  UNIQUE (content_release_id, form_id),
  CHECK (type2_id IS NULL OR type2_id <> type1_id)
);

CREATE TABLE move_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  move_id UUID NOT NULL REFERENCES moves(id),
  display_name TEXT NOT NULL,
  type_id UUID NOT NULL REFERENCES pokemon_types(id),
  category TEXT NOT NULL CHECK (category IN ('PHYSICAL', 'SPECIAL', 'STATUS')),
  power INTEGER NULL CHECK (power IS NULL OR power >= 0),
  accuracy INTEGER NULL CHECK (accuracy IS NULL OR accuracy BETWEEN 0 AND 100),
  priority SMALLINT NOT NULL DEFAULT 0,
  max_pp SMALLINT NULL CHECK (max_pp IS NULL OR max_pp > 0),
  effect_key TEXT NULL,
  effect_config JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(effect_config) = 'object'),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (content_release_id, move_id)
);

CREATE TABLE ability_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  ability_id UUID NOT NULL REFERENCES abilities(id),
  display_name TEXT NOT NULL,
  effect_key TEXT NULL,
  effect_config JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(effect_config) = 'object'),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (content_release_id, ability_id)
);

CREATE TABLE item_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  item_id UUID NOT NULL REFERENCES items(id),
  display_name TEXT NOT NULL,
  item_kind TEXT NOT NULL,
  effect_key TEXT NULL,
  effect_config JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(effect_config) = 'object'),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (content_release_id, item_id)
);

CREATE TABLE nature_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  nature_id UUID NOT NULL REFERENCES natures(id),
  display_name TEXT NOT NULL,
  increased_stat TEXT NULL CHECK (increased_stat IS NULL OR increased_stat IN ('ATTACK', 'DEFENSE', 'SP_ATTACK', 'SP_DEFENSE', 'SPEED')),
  decreased_stat TEXT NULL CHECK (decreased_stat IS NULL OR decreased_stat IN ('ATTACK', 'DEFENSE', 'SP_ATTACK', 'SP_DEFENSE', 'SPEED')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (content_release_id, nature_id),
  CHECK (
    (increased_stat IS NULL AND decreased_stat IS NULL)
    OR (increased_stat IS NOT NULL AND decreased_stat IS NOT NULL AND increased_stat <> decreased_stat)
  )
);

CREATE TABLE effect_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  effect_id UUID NOT NULL REFERENCES effects(id),
  scope TEXT NOT NULL CHECK (scope IN ('PLAYER', 'POKEMON', 'BATTLE_PARTICIPANT', 'AREA')),
  stacking_policy TEXT NOT NULL,
  duration_model TEXT NOT NULL,
  rules JSONB NOT NULL CHECK (jsonb_typeof(rules) = 'object'),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (content_release_id, effect_id)
);

CREATE TABLE region_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  region_id UUID NOT NULL REFERENCES regions(id),
  display_name TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  data JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(data) = 'object'),
  UNIQUE (content_release_id, region_id)
);

CREATE TABLE area_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  area_id UUID NOT NULL REFERENCES areas(id),
  display_name TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  data JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(data) = 'object'),
  UNIQUE (content_release_id, area_id)
);

CREATE TABLE area_connection_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  connection_id UUID NOT NULL REFERENCES area_connections(id),
  access_rule JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(access_rule) = 'object'),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (content_release_id, connection_id)
);

CREATE TABLE type_matchups (
  ruleset_id UUID NOT NULL REFERENCES rulesets(id),
  attacking_type_id UUID NOT NULL REFERENCES pokemon_types(id),
  defending_type_id UUID NOT NULL REFERENCES pokemon_types(id),
  multiplier_basis_points INTEGER NOT NULL CHECK (multiplier_basis_points >= 0),
  PRIMARY KEY (ruleset_id, attacking_type_id, defending_type_id)
);

CREATE TABLE players (
  id UUID PRIMARY KEY,
  status TEXT NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED', 'ARCHIVED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0)
);

CREATE TABLE player_identities (
  id UUID PRIMARY KEY,
  player_id UUID NOT NULL REFERENCES players(id),
  provider TEXT NOT NULL,
  external_id TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('ACTIVE', 'REVOKED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ NULL,
  UNIQUE (provider, external_id),
  CHECK ((status = 'REVOKED' AND revoked_at IS NOT NULL) OR status = 'ACTIVE')
);

CREATE INDEX idx_player_identities_player ON player_identities(player_id);

CREATE TABLE player_profiles (
  player_id UUID PRIMARY KEY REFERENCES players(id),
  trainer_name TEXT NOT NULL,
  origin_region_id UUID NULL REFERENCES regions(id),
  locale TEXT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0)
);

CREATE TABLE onboarding_states (
  player_id UUID PRIMARY KEY REFERENCES players(id),
  state TEXT NOT NULL CHECK (state IN ('NEW', 'PROFILE_CREATED', 'REGION_SELECTED', 'STARTER_PENDING', 'STARTER_GRANTED', 'COMPLETE')),
  starter_claim_key TEXT NULL,
  completed_at TIMESTAMPTZ NULL,
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK ((state = 'COMPLETE' AND completed_at IS NOT NULL) OR state <> 'COMPLETE')
);

CREATE TABLE trainer_progression (
  player_id UUID PRIMARY KEY REFERENCES players(id),
  level SMALLINT NOT NULL DEFAULT 1 CHECK (level >= 1),
  progression_points BIGINT NOT NULL DEFAULT 0 CHECK (progression_points >= 0),
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE trainer_progress_ledger (
  id UUID PRIMARY KEY,
  player_id UUID NOT NULL REFERENCES players(id),
  delta BIGINT NOT NULL CHECK (delta <> 0),
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  reason TEXT NULL,
  actor_type TEXT NOT NULL,
  actor_id UUID NULL,
  idempotency_scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  correlation_id UUID NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (idempotency_scope, idempotency_key)
);

CREATE INDEX idx_trainer_progress_ledger_player_created ON trainer_progress_ledger(player_id, created_at DESC);

CREATE TABLE trainer_unlocks (
  player_id UUID NOT NULL REFERENCES players(id),
  unlock_key TEXT NOT NULL,
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'REVOKED')),
  unlocked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ NULL,
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
  PRIMARY KEY (player_id, unlock_key),
  CHECK (
    (status = 'ACTIVE' AND revoked_at IS NULL)
    OR (status = 'REVOKED' AND revoked_at IS NOT NULL)
  )
);

CREATE TABLE pokemon_instances (
  id UUID PRIMARY KEY,
  owner_player_id UUID NOT NULL REFERENCES players(id),
  form_id UUID NOT NULL REFERENCES pokemon_forms(id),
  nickname TEXT NULL,
  level SMALLINT NOT NULL CHECK (level >= 1),
  xp BIGINT NOT NULL DEFAULT 0 CHECK (xp >= 0),
  current_hp INTEGER NOT NULL CHECK (current_hp >= 0),
  gender TEXT NULL,
  shiny BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ARCHIVED')),
  archived_at TIMESTAMPTZ NULL,
  ability_id UUID NULL REFERENCES abilities(id),
  origin_type TEXT NOT NULL,
  origin_id UUID NULL,
  captured_at TIMESTAMPTZ NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (id, owner_player_id),
  CHECK (
    (status = 'ACTIVE' AND archived_at IS NULL)
    OR (status = 'ARCHIVED' AND archived_at IS NOT NULL)
  )
);

CREATE INDEX idx_pokemon_instances_owner_status_created
  ON pokemon_instances(owner_player_id, status, created_at DESC);

CREATE TABLE pokemon_training_values (
  pokemon_instance_id UUID PRIMARY KEY REFERENCES pokemon_instances(id),
  nature_id UUID NULL REFERENCES natures(id),
  iv_hp SMALLINT NULL CHECK (iv_hp IS NULL OR iv_hp BETWEEN 0 AND 31),
  iv_attack SMALLINT NULL CHECK (iv_attack IS NULL OR iv_attack BETWEEN 0 AND 31),
  iv_defense SMALLINT NULL CHECK (iv_defense IS NULL OR iv_defense BETWEEN 0 AND 31),
  iv_sp_attack SMALLINT NULL CHECK (iv_sp_attack IS NULL OR iv_sp_attack BETWEEN 0 AND 31),
  iv_sp_defense SMALLINT NULL CHECK (iv_sp_defense IS NULL OR iv_sp_defense BETWEEN 0 AND 31),
  iv_speed SMALLINT NULL CHECK (iv_speed IS NULL OR iv_speed BETWEEN 0 AND 31),
  ev_hp SMALLINT NULL CHECK (ev_hp IS NULL OR ev_hp >= 0),
  ev_attack SMALLINT NULL CHECK (ev_attack IS NULL OR ev_attack >= 0),
  ev_defense SMALLINT NULL CHECK (ev_defense IS NULL OR ev_defense >= 0),
  ev_sp_attack SMALLINT NULL CHECK (ev_sp_attack IS NULL OR ev_sp_attack >= 0),
  ev_sp_defense SMALLINT NULL CHECK (ev_sp_defense IS NULL OR ev_sp_defense >= 0),
  ev_speed SMALLINT NULL CHECK (ev_speed IS NULL OR ev_speed >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE pokemon_move_slots (
  pokemon_instance_id UUID NOT NULL REFERENCES pokemon_instances(id),
  slot_no SMALLINT NOT NULL CHECK (slot_no BETWEEN 1 AND 4),
  move_id UUID NOT NULL REFERENCES moves(id),
  pp_current SMALLINT NULL CHECK (pp_current IS NULL OR pp_current >= 0),
  learned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (pokemon_instance_id, slot_no)
);

CREATE TABLE pokemon_roster_slots (
  pokemon_instance_id UUID PRIMARY KEY,
  player_id UUID NOT NULL,
  placement_kind TEXT NOT NULL CHECK (placement_kind IN ('TEAM', 'BOX')),
  box_no INTEGER NULL,
  slot_no INTEGER NOT NULL CHECK (slot_no > 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (pokemon_instance_id, player_id) REFERENCES pokemon_instances(id, owner_player_id),
  CHECK (
    (placement_kind = 'TEAM' AND box_no IS NULL AND slot_no BETWEEN 1 AND 6)
    OR
    (placement_kind = 'BOX' AND box_no IS NOT NULL AND box_no > 0)
  )
);

CREATE UNIQUE INDEX uq_pokemon_team_slot ON pokemon_roster_slots(player_id, slot_no) WHERE placement_kind = 'TEAM';
CREATE UNIQUE INDEX uq_pokemon_box_slot ON pokemon_roster_slots(player_id, box_no, slot_no) WHERE placement_kind = 'BOX';
CREATE INDEX idx_pokemon_roster_player_placement ON pokemon_roster_slots(player_id, placement_kind, slot_no);

CREATE TABLE pokemon_persistent_conditions (
  pokemon_instance_id UUID NOT NULL REFERENCES pokemon_instances(id),
  condition_key TEXT NOT NULL,
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NULL,
  data JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(data) = 'object'),
  PRIMARY KEY (pokemon_instance_id, condition_key),
  CHECK (expires_at IS NULL OR expires_at > applied_at)
);

CREATE TABLE pokemon_history_events (
  id UUID PRIMARY KEY,
  pokemon_instance_id UUID NOT NULL REFERENCES pokemon_instances(id),
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  actor_type TEXT NOT NULL,
  actor_id UUID NULL,
  correlation_id UUID NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_pokemon_history_instance_occurred ON pokemon_history_events(pokemon_instance_id, occurred_at DESC);

CREATE TABLE starter_grants (
  id UUID PRIMARY KEY,
  player_id UUID NOT NULL REFERENCES players(id),
  idempotency_key TEXT NOT NULL UNIQUE,
  pokemon_instance_id UUID NOT NULL UNIQUE REFERENCES pokemon_instances(id),
  granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (player_id)
);

CREATE TABLE inventory_balances (
  player_id UUID NOT NULL REFERENCES players(id),
  item_id UUID NOT NULL REFERENCES items(id),
  quantity BIGINT NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (player_id, item_id)
);

CREATE TABLE inventory_ledger (
  id UUID PRIMARY KEY,
  player_id UUID NOT NULL REFERENCES players(id),
  item_id UUID NOT NULL REFERENCES items(id),
  delta BIGINT NOT NULL CHECK (delta <> 0),
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  reason TEXT NULL,
  actor_type TEXT NOT NULL,
  actor_id UUID NULL,
  idempotency_scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  correlation_id UUID NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (idempotency_scope, idempotency_key)
);

CREATE INDEX idx_inventory_ledger_player_created ON inventory_ledger(player_id, created_at DESC);
CREATE INDEX idx_inventory_ledger_player_item_created ON inventory_ledger(player_id, item_id, created_at DESC);

CREATE TABLE wallet_balances (
  player_id UUID NOT NULL REFERENCES players(id),
  currency_id UUID NOT NULL REFERENCES currency_definitions(id),
  amount BIGINT NOT NULL DEFAULT 0,
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (player_id, currency_id)
);

CREATE TABLE wallet_ledger (
  id UUID PRIMARY KEY,
  player_id UUID NOT NULL REFERENCES players(id),
  currency_id UUID NOT NULL REFERENCES currency_definitions(id),
  delta BIGINT NOT NULL CHECK (delta <> 0),
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  reason TEXT NULL,
  actor_type TEXT NOT NULL,
  actor_id UUID NULL,
  idempotency_scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  correlation_id UUID NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (idempotency_scope, idempotency_key)
);

CREATE INDEX idx_wallet_ledger_player_created ON wallet_ledger(player_id, created_at DESC);
CREATE INDEX idx_wallet_ledger_player_currency_created ON wallet_ledger(player_id, currency_id, created_at DESC);

CREATE TABLE player_locations (
  player_id UUID PRIMARY KEY REFERENCES players(id),
  area_id UUID NOT NULL REFERENCES areas(id),
  entered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0)
);

CREATE TABLE encounter_table_revisions (
  id UUID PRIMARY KEY,
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  encounter_table_id UUID NOT NULL REFERENCES encounter_tables(id),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  conditions JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(conditions) = 'object'),
  UNIQUE (content_release_id, encounter_table_id)
);

CREATE TABLE encounter_entries (
  id UUID PRIMARY KEY,
  encounter_table_revision_id UUID NOT NULL REFERENCES encounter_table_revisions(id) ON DELETE CASCADE,
  form_id UUID NOT NULL REFERENCES pokemon_forms(id),
  weight BIGINT NOT NULL CHECK (weight > 0),
  min_level SMALLINT NOT NULL CHECK (min_level >= 1),
  max_level SMALLINT NOT NULL CHECK (max_level >= 1),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  conditions JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(conditions) = 'object'),
  CHECK (max_level >= min_level)
);

CREATE INDEX idx_encounter_entries_revision ON encounter_entries(encounter_table_revision_id);

CREATE TABLE encounters (
  id UUID PRIMARY KEY,
  player_id UUID NOT NULL REFERENCES players(id),
  area_id UUID NOT NULL REFERENCES areas(id),
  status TEXT NOT NULL CHECK (status IN ('CREATED', 'PRESENTED', 'ENGAGED', 'CAPTURE_RESOLVING', 'IN_BATTLE', 'CAPTURED', 'FLED', 'EXPIRED', 'CLOSED')),
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  ruleset_id UUID NOT NULL REFERENCES rulesets(id),
  rng_seed_ciphertext BYTEA NOT NULL CHECK (octet_length(rng_seed_ciphertext) = 32),
  rng_seed_iv BYTEA NOT NULL CHECK (octet_length(rng_seed_iv) = 12),
  rng_seed_auth_tag BYTEA NOT NULL CHECK (octet_length(rng_seed_auth_tag) = 16),
  rng_seed_key_version SMALLINT NOT NULL CHECK (rng_seed_key_version > 0),
  rng_counter BIGINT NOT NULL DEFAULT 0 CHECK (rng_counter >= 0),
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uq_player_active_encounter ON encounters(player_id)
  WHERE status IN ('CREATED', 'PRESENTED', 'ENGAGED', 'CAPTURE_RESOLVING', 'IN_BATTLE');
CREATE INDEX idx_encounters_player_created ON encounters(player_id, created_at DESC);

CREATE TABLE encounter_snapshots (
  encounter_id UUID PRIMARY KEY REFERENCES encounters(id) ON DELETE CASCADE,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  pokemon_snapshot JSONB NOT NULL CHECK (jsonb_typeof(pokemon_snapshot) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE battles (
  id UUID PRIMARY KEY,
  battle_type TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('CREATED', 'ACTIVE', 'RESOLVING_TURN', 'WON', 'LOST', 'FLED', 'DRAW', 'CANCELLED')),
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  ruleset_id UUID NOT NULL REFERENCES rulesets(id),
  encounter_id UUID NULL UNIQUE REFERENCES encounters(id),
  turn_number INTEGER NOT NULL DEFAULT 0 CHECK (turn_number >= 0),
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  rng_seed_ciphertext BYTEA NOT NULL CHECK (octet_length(rng_seed_ciphertext) = 32),
  rng_seed_iv BYTEA NOT NULL CHECK (octet_length(rng_seed_iv) = 12),
  rng_seed_auth_tag BYTEA NOT NULL CHECK (octet_length(rng_seed_auth_tag) = 16),
  rng_seed_key_version SMALLINT NOT NULL CHECK (rng_seed_key_version > 0),
  rng_counter BIGINT NOT NULL DEFAULT 0 CHECK (rng_counter >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at TIMESTAMPTZ NULL
);

CREATE TABLE battle_sides (
  id UUID PRIMARY KEY,
  battle_id UUID NOT NULL REFERENCES battles(id) ON DELETE CASCADE,
  side_no SMALLINT NOT NULL CHECK (side_no > 0),
  controller_kind TEXT NOT NULL CHECK (controller_kind IN ('PLAYER', 'WILD', 'NPC', 'SYSTEM')),
  player_id UUID NULL REFERENCES players(id),
  result TEXT NULL CHECK (result IS NULL OR result IN ('WON', 'LOST', 'FLED', 'DRAW', 'CANCELLED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (battle_id, side_no),
  UNIQUE (id, battle_id),
  CHECK (
    (controller_kind = 'PLAYER' AND player_id IS NOT NULL)
    OR (controller_kind <> 'PLAYER' AND player_id IS NULL)
  )
);

CREATE INDEX idx_battle_sides_player ON battle_sides(player_id) WHERE player_id IS NOT NULL;

CREATE TABLE battle_participants (
  id UUID PRIMARY KEY,
  battle_id UUID NOT NULL REFERENCES battles(id) ON DELETE CASCADE,
  battle_side_id UUID NOT NULL,
  pokemon_instance_id UUID NULL REFERENCES pokemon_instances(id),
  participant_kind TEXT NOT NULL CHECK (participant_kind IN ('PLAYER_POKEMON', 'WILD_POKEMON', 'NPC_POKEMON')),
  roster_position SMALLINT NOT NULL CHECK (roster_position > 0),
  active_member BOOLEAN NOT NULL DEFAULT TRUE,
  snapshot JSONB NOT NULL CHECK (jsonb_typeof(snapshot) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (id, battle_id),
  UNIQUE (battle_side_id, roster_position),
  FOREIGN KEY (battle_side_id, battle_id) REFERENCES battle_sides(id, battle_id),
  CHECK ((participant_kind = 'PLAYER_POKEMON' AND pokemon_instance_id IS NOT NULL) OR participant_kind <> 'PLAYER_POKEMON')
);

CREATE INDEX idx_battle_participants_battle ON battle_participants(battle_id, battle_side_id);

CREATE TABLE battle_actions (
  id UUID PRIMARY KEY,
  battle_id UUID NOT NULL REFERENCES battles(id) ON DELETE CASCADE,
  actor_participant_id UUID NOT NULL,
  action_type TEXT NOT NULL,
  payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  expected_battle_version BIGINT NOT NULL CHECK (expected_battle_version >= 0),
  idempotency_key TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('RECEIVED', 'ACCEPTED', 'REJECTED', 'RESOLVED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ NULL,
  FOREIGN KEY (actor_participant_id, battle_id) REFERENCES battle_participants(id, battle_id)
);

CREATE INDEX idx_battle_actions_battle_created ON battle_actions(battle_id, created_at);

CREATE TABLE battle_state_snapshots (
  battle_id UUID NOT NULL REFERENCES battles(id) ON DELETE CASCADE,
  version BIGINT NOT NULL CHECK (version >= 0),
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  state JSONB NOT NULL CHECK (jsonb_typeof(state) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (battle_id, version)
);

CREATE TABLE battle_events (
  id UUID PRIMARY KEY,
  battle_id UUID NOT NULL REFERENCES battles(id) ON DELETE CASCADE,
  seq BIGINT NOT NULL CHECK (seq > 0),
  battle_version BIGINT NOT NULL CHECK (battle_version >= 0),
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  causation_id UUID NULL,
  correlation_id UUID NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (battle_id, seq)
);

CREATE INDEX idx_battle_events_battle_version ON battle_events(battle_id, battle_version);

CREATE TABLE capture_attempts (
  id UUID PRIMARY KEY,
  player_id UUID NOT NULL REFERENCES players(id),
  encounter_id UUID NOT NULL REFERENCES encounters(id),
  battle_id UUID NULL REFERENCES battles(id),
  ball_item_id UUID NOT NULL REFERENCES items(id),
  idempotency_key TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('PENDING', 'FAILED', 'CAPTURED')),
  probability_basis_points INTEGER NOT NULL CHECK (probability_basis_points BETWEEN 0 AND 10000),
  roll_basis_points INTEGER NOT NULL CHECK (roll_basis_points BETWEEN 0 AND 9999),
  pokemon_instance_id UUID NULL UNIQUE REFERENCES pokemon_instances(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ NULL,
  CHECK ((status = 'CAPTURED' AND pokemon_instance_id IS NOT NULL AND resolved_at IS NOT NULL) OR status <> 'CAPTURED'),
  CHECK ((status = 'FAILED' AND pokemon_instance_id IS NULL AND resolved_at IS NOT NULL) OR status <> 'FAILED')
);

CREATE INDEX idx_capture_attempts_player_created ON capture_attempts(player_id, created_at DESC);

CREATE TABLE player_pokedex_species (
  player_id UUID NOT NULL REFERENCES players(id),
  species_id UUID NOT NULL REFERENCES pokemon_species(id),
  seen_count BIGINT NOT NULL DEFAULT 0 CHECK (seen_count >= 0),
  caught_count BIGINT NOT NULL DEFAULT 0 CHECK (caught_count >= 0),
  first_seen_at TIMESTAMPTZ NULL,
  last_seen_at TIMESTAMPTZ NULL,
  first_caught_at TIMESTAMPTZ NULL,
  last_caught_at TIMESTAMPTZ NULL,
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
  PRIMARY KEY (player_id, species_id),
  CHECK (caught_count <= seen_count)
);

CREATE INDEX idx_player_pokedex_player ON player_pokedex_species(player_id);

CREATE TABLE active_effects (
  id UUID PRIMARY KEY,
  effect_id UUID NOT NULL REFERENCES effects(id),
  content_release_id UUID NOT NULL REFERENCES content_releases(id),
  player_id UUID NULL REFERENCES players(id),
  pokemon_instance_id UUID NULL REFERENCES pokemon_instances(id),
  battle_participant_id UUID NULL REFERENCES battle_participants(id),
  area_id UUID NULL REFERENCES areas(id),
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  stacks INTEGER NOT NULL DEFAULT 1 CHECK (stacks > 0),
  config JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(config) = 'object'),
  starts_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NULL,
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
  CHECK (num_nonnulls(player_id, pokemon_instance_id, battle_participant_id, area_id) = 1),
  CHECK (expires_at IS NULL OR expires_at > starts_at)
);

CREATE INDEX idx_active_effects_player ON active_effects(player_id) WHERE player_id IS NOT NULL;
CREATE INDEX idx_active_effects_pokemon ON active_effects(pokemon_instance_id) WHERE pokemon_instance_id IS NOT NULL;
CREATE INDEX idx_active_effects_battle_participant ON active_effects(battle_participant_id) WHERE battle_participant_id IS NOT NULL;
CREATE INDEX idx_active_effects_area ON active_effects(area_id) WHERE area_id IS NOT NULL;

CREATE TABLE inbox_messages (
  id UUID PRIMARY KEY,
  provider TEXT NOT NULL,
  external_message_id TEXT NOT NULL,
  player_id UUID NULL REFERENCES players(id),
  payload_hash TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED')),
  result_ref_type TEXT NULL,
  result_ref_id UUID NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ NULL,
  last_error_code TEXT NULL,
  UNIQUE (provider, external_message_id)
);

CREATE INDEX idx_inbox_status_received ON inbox_messages(status, received_at);

CREATE TABLE outbox_messages (
  id UUID PRIMARY KEY,
  channel TEXT NOT NULL,
  destination_ref TEXT NOT NULL,
  message_type TEXT NOT NULL,
  payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  idempotency_key TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'FAILED', 'DEAD')),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  next_attempt_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ NULL,
  last_error_code TEXT NULL,
  CHECK ((status = 'SENT' AND sent_at IS NOT NULL) OR status <> 'SENT')
);

CREATE INDEX idx_outbox_status_next_created ON outbox_messages(status, next_attempt_at, created_at);

CREATE TABLE audit_events (
  id UUID PRIMARY KEY,
  actor_type TEXT NOT NULL,
  actor_id UUID NULL,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id UUID NULL,
  risk_tier SMALLINT NULL CHECK (risk_tier IS NULL OR risk_tier BETWEEN 0 AND 4),
  reason TEXT NULL,
  before_data JSONB NULL CHECK (before_data IS NULL OR jsonb_typeof(before_data) = 'object'),
  after_data JSONB NULL CHECK (after_data IS NULL OR jsonb_typeof(after_data) = 'object'),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  correlation_id UUID NULL,
  causation_id UUID NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_target_occurred ON audit_events(target_type, target_id, occurred_at DESC);
CREATE INDEX idx_audit_actor_occurred ON audit_events(actor_type, actor_id, occurred_at DESC);
CREATE INDEX idx_audit_correlation ON audit_events(correlation_id);

CREATE TABLE admin_operations (
  id UUID PRIMARY KEY,
  principal_id UUID NOT NULL REFERENCES admin_principals(id),
  capability_key TEXT NOT NULL,
  operation_type TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id UUID NULL,
  risk_tier SMALLINT NOT NULL CHECK (risk_tier BETWEEN 0 AND 4),
  status TEXT NOT NULL CHECK (status IN ('DRAFT', 'VALIDATED', 'SIMULATED', 'PENDING_CONFIRMATION', 'PENDING_APPROVAL', 'APPLIED', 'REJECTED', 'FAILED', 'COMPENSATED')),
  reason TEXT NOT NULL,
  expected_revision BIGINT NULL CHECK (expected_revision IS NULL OR expected_revision >= 0),
  idempotency_key TEXT NOT NULL UNIQUE,
  input JSONB NOT NULL CHECK (jsonb_typeof(input) = 'object'),
  result JSONB NULL CHECK (result IS NULL OR jsonb_typeof(result) = 'object'),
  correlation_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  applied_at TIMESTAMPTZ NULL
);

CREATE INDEX idx_admin_operations_principal_created ON admin_operations(principal_id, created_at DESC);
CREATE INDEX idx_admin_operations_target_created ON admin_operations(target_type, target_id, created_at DESC);

CREATE TABLE admin_operation_changes (
  id UUID PRIMARY KEY,
  admin_operation_id UUID NOT NULL REFERENCES admin_operations(id) ON DELETE CASCADE,
  resource_type TEXT NOT NULL,
  resource_id UUID NULL,
  before_data JSONB NULL CHECK (before_data IS NULL OR jsonb_typeof(before_data) = 'object'),
  after_data JSONB NULL CHECK (after_data IS NULL OR jsonb_typeof(after_data) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_admin_operation_changes_operation ON admin_operation_changes(admin_operation_id, created_at);
