engineStrict: true
saveExact: true
allowBuilds:
  '@whiskeysockets/baileys': false
  esbuild: true
  protobufjs: false
patchedDependencies:
  '@whiskeysockets/baileys@7.0.0-rc14': patches/@whiskeysockets__baileys@7.0.0-rc14.patch
