export const ADMIN_ERROR_CODES = {
  INVALID_INPUT: "ADMIN_INVALID_INPUT",
  OPERATION_NOT_REGISTERED: "ADMIN_OPERATION_NOT_REGISTERED",
  OPERATION_KIND_MISMATCH: "ADMIN_OPERATION_KIND_MISMATCH",
  PRINCIPAL_NOT_FOUND: "ADMIN_PRINCIPAL_NOT_FOUND",
  PRINCIPAL_DISABLED: "ADMIN_PRINCIPAL_DISABLED",
  AUTHORIZATION_DENIED: "ADMIN_AUTHORIZATION_DENIED",
  CAPABILITY_POLICY_DRIFT: "ADMIN_CAPABILITY_POLICY_DRIFT",
  OPERATION_POLICY_DRIFT: "ADMIN_OPERATION_POLICY_DRIFT",
  REASON_REQUIRED: "ADMIN_REASON_REQUIRED",
  EXPECTED_REVISION_REQUIRED: "ADMIN_EXPECTED_REVISION_REQUIRED",
  IDEMPOTENCY_CONFLICT: "ADMIN_IDEMPOTENCY_CONFLICT",
  OPERATION_NOT_FOUND: "ADMIN_OPERATION_NOT_FOUND",
  INVALID_OPERATION_STATE: "ADMIN_INVALID_OPERATION_STATE",
  SELF_APPROVAL_FORBIDDEN: "ADMIN_SELF_APPROVAL_FORBIDDEN",
  REVISION_CONFLICT: "ADMIN_REVISION_CONFLICT",
  TARGET_NOT_FOUND: "ADMIN_TARGET_NOT_FOUND",
} as const;

export type AdminErrorCode = (typeof ADMIN_ERROR_CODES)[keyof typeof ADMIN_ERROR_CODES];

export class AdminError extends Error {
  public constructor(
    public readonly code: AdminErrorCode,
    message: string,
    public readonly details?: Readonly<Record<string, unknown>>,
  ) {
    super(message);
    this.name = "AdminError";
  }
}
