export const OWNER_SECURITY_ADMIN_ROLE = "OWNER_SECURITY_ADMIN" as const;

export const ADMIN_CAPABILITIES = [
  ["player.read", 0],
  ["player.read_sensitive", 0],
  ["player.registration.read", 0],
  ["pokemon.read", 0],
  ["inventory.read", 0],
  ["economy.read", 0],
  ["progression.read", 0],
  ["pokedex.read", 0],
  ["world.read", 0],
  ["battle.read", 0],
  ["effects.read", 0],
  ["audit.read", 0],
  ["admin_operation.read", 0],
  ["player.profile.edit", 1],
  ["player.location.correct", 1],
  ["player.onboarding.support", 1],
  ["player.registration.request_changes", 1],
  ["pokemon.roster.manage", 1],
  ["encounter.support", 1],
  ["battle.support", 1],
  ["player.registration.approve", 2],
  ["player.registration.reject", 2],
  ["progression.adjust", 2],
  ["progression.unlock.manage", 2],
  ["inventory.adjust", 2],
  ["wallet.adjust", 2],
  ["reward.grant", 2],
  ["effect.apply", 2],
  ["effect.remove", 2],
  ["pokemon.create", 3],
  ["pokemon.edit.basic", 3],
  ["pokemon.edit.mechanics", 3],
  ["pokemon.moves.edit", 3],
  ["pokemon.training.edit", 3],
  ["pokemon.ability.edit", 3],
  ["pokemon.transfer", 3],
  ["pokemon.archive_remove", 3],
  ["pokemon.restore", 3],
  ["pokedex.correct", 3],
  ["encounter.force_close", 3],
  ["battle.force_cancel", 3],
  ["battle.correct_state", 3],
  ["content.draft.create", 3],
  ["content.draft.edit", 3],
  ["content.validate", 3],
  ["content.archive", 3],
  ["batch.preview", 2],
  ["batch.execute.low_risk", 3],
  ["admin_operation.compensate", 3],
  ["player.reset.full", 4],
  ["content.publish", 4],
  ["content.rollback_release", 4],
  ["batch.execute.high_risk", 4],
  ["admin.role.assign", 4],
  ["admin.role.manage", 4],
  ["admin.capability.manage", 4],
  ["admin.override.invariant", 4],
] as const;

export type AdminCapabilityKey = (typeof ADMIN_CAPABILITIES)[number][0];

export const ADMIN_ROLE_CAPABILITIES: Readonly<Record<string, readonly AdminCapabilityKey[]>> = {
  SUPPORT: [
    "player.read",
    "pokemon.read",
    "inventory.read",
    "economy.read",
    "progression.read",
    "pokedex.read",
    "world.read",
    "battle.read",
    "effects.read",
    "player.profile.edit",
    "player.location.correct",
    "player.onboarding.support",
    "pokemon.roster.manage",
    "encounter.support",
    "battle.support",
  ],
  GAME_MASTER: [
    "player.read",
    "pokemon.read",
    "inventory.read",
    "progression.read",
    "world.read",
    "battle.read",
    "effects.read",
    "encounter.support",
    "battle.support",
    "reward.grant",
    "effect.apply",
    "effect.remove",
  ],
  ECONOMY_ADMIN: [
    "player.read",
    "inventory.read",
    "economy.read",
    "progression.read",
    "inventory.adjust",
    "wallet.adjust",
    "progression.adjust",
    "progression.unlock.manage",
    "batch.preview",
    "batch.execute.low_risk",
  ],
  POKEMON_ADMIN: [
    "player.read",
    "pokemon.read",
    "pokemon.create",
    "pokemon.edit.basic",
    "pokemon.edit.mechanics",
    "pokemon.moves.edit",
    "pokemon.training.edit",
    "pokemon.ability.edit",
    "pokemon.roster.manage",
    "pokemon.transfer",
    "pokemon.archive_remove",
    "pokemon.restore",
    "pokedex.correct",
  ],
  CONTENT_EDITOR: ["content.draft.create", "content.draft.edit", "content.validate"],
  CONTENT_PUBLISHER: ["content.validate", "content.publish", "content.archive"],
  SENIOR_ADMIN: ADMIN_CAPABILITIES.filter(([, risk]) => risk <= 3).map(([key]) => key),
  OWNER_SECURITY_ADMIN: ADMIN_CAPABILITIES.map(([key]) => key),
};
